### ISSUE TITLE
Rename and move staff_list.php page template

### ISSUE THREAD

**Issue by jschumann** [wrdsb/wordpress-theme#151]
The template file should be named staff-list.php and should be located in the page-templates directory.

**Comment by suzannezc** [comment]
Same caveat as issue #152 with more reach as it impacts all school sites.

http://nacin.com/2012/03/29/page-templates-in-subdirectories-new-in-wordpress-3-4/

>Updated… Caution: Renaming a page template — and that includes moving all of top-level page templates into a directory — will unassign that page template for all pages currently using it. This is a new tool in your toolbox, but use it wisely.

**Comment by suzannezc** [comment]
Closed with 0185ea8befd335d33473227e9ea0a99df0137031
