### ISSUE TITLE
Rename and move school_page.php template

### ISSUE THREAD

**Issue by jschumann** [wrdsb/wordpress-theme#152]
The template file should be named schools-list.php and should be located in the page-templates directory.

**Comment by suzannezc** [comment]
http://nacin.com/2012/03/29/page-templates-in-subdirectories-new-in-wordpress-3-4/

>Updated… Caution: Renaming a page template — and that includes moving all of top-level page templates into a directory — will unassign that page template for all pages currently using it. This is a new tool in your toolbox, but use it wisely.

**Comment by jschumann** [comment]
Good to know

**Comment by suzannezc** [comment]
Closed with https://github.com/wrdsb/wordpress-theme/commit/e4af3fdbd3dbd7cb84492cb8c4ec13ee5b78e8ec
