### ISSUE TITLE
img vs. images

### ISSUE THREAD

**Issue by jschumann** [wrdsb/wordpress-theme#157]
Why do we have both?

**Comment by suzannezc** [comment]
context?

**Comment by jschumann** [comment]
There are two image directories in this repository: img and images

**Comment by suzannezc** [comment]
Looks like /img/ came from bootstrap, /images/ is where we've put other images. Including a whole whack of no longer required library images.

**Comment by suzannezc** [comment]
Do you have a preference which version we use?

**Comment by jschumann** [comment]
If we're going to merge them, let's keep Bootstrap's /img

Is there any value in keeping them separate, and doing the same with CSS and JavaScript?

**Comment by suzannezc** [comment]
Discussed, will merge /images/ into /img/ and keep all CSS and JavaScript together. 

Closed with 4eb54fb9d7c5806771bc2654439182367cc75728
