### ISSUE TITLE
If page body empty, give me a menu

### ISSUE THREAD

**Issue by jschumann** [wrdsb/wordpress-theme#395]
If page body/content is empty, display a menu of child pages where I'd usually see content.

**Comment by jschumann** [comment]
Include the page excerpt from #396, if set.

**Comment by jschumann** [comment]
In content-page.php:

<?php the_title('<h1>', '</h1>'); ?>
<?php
  if ($post->post_content == '') {
    $children = get_pages(array(
      'sort_order' => 'ASC',
      'sort_column' => 'menu_order',
      'hierarchical' => 0,
      'parent' => $post->ID,
      'post_type' => 'page',
    ));
    // TODO: Make this a DL
    echo '<ul>';
      foreach ($children as $child) {
        echo '<li>';
        echo '<strong><a href="'.get_permalink($child->ID).'">'.$child->post_title.'</a></strong>';
        echo '<p>';
          echo get_the_excerpt($child);
        echo '</p>';
        echo '</li>';
      }
    echo '</ul>';
  } else {
    the_content();
  }
?>
<?php
        $igc=0;

**Comment by suzannezc** [comment]
Closed with https://github.com/wrdsb/wordpress-theme/commit/5aa9a9dff0f5b060bd4260e99d9627f68f6e86a9
