### ISSUE TITLE
Add Max Mega Menu Pro to www

### ISSUE THREAD

**Issue by suzannezc** [wrdsb/wordpress-theme#524]
## Prepare tracking

- [x] Copy this task list to an issue labelled deployment
- [x] Name issue: "add `plugin name` to `install(s)`"
- [x] Install any base plugins required `Max Mega Menu` 
- [x] update task list with any relevant changes to this list

## New Plugin Release

- [x] Audition on WPLabs and wwwwrdsbdev (staging)
- [x] Identify installs/sites for use
- [x] Internal training on use
- [x] External training on use
- [x] Add to documentation
- [x] Closed beta
- [x] Open beta
- [x] Full release on all identified installs/sites
- [x] Network Activate
- [x] Configure at the network level
- [x] Configure for each site
- - [x] planning
- - [x] pic
- - [x] facilities
- - [x] kindergarten
- - [x] beforeafter
- - [x] careers
- - [x] wefi
- - [x] french
- - [x] register
- - [x] returntoschool
- - [x] labour
- - [x] www (main site)

## After theme is updated to add code snippet (see: https://github.com/wrdsb/wordpress-theme/issues/523)

 - [x] Add logo menu item and configure it.
 - [x] Add Search menu item and configure it.
 - [x] Set mobile responsive breakout to 1150px
 - [x] Configure Menu items to follow grid sub-menu layout
 
- [x] Configure as above for each site
- - [x] planning
- - [x] pic
- - [x] facilities
- - [x] kindergarten
- - [x] beforeafter
- - [x] careers
- - [x] wefi
- - [x] french
- - [x] register
- - [x] returntoschool
- - [x] labour
- - [x] www (main site)

**Comment by suzannezc** [comment]
archived 

- esu
- learning-services
- board-meetings
- safeschools
- catc
- continuing-education
- alternative-education
- ctcc

**Comment by suzannezc** [comment]
### Emergency fix

- Removed Google Analytics + 
- Network-enabled GADWP

- [ ] Configure for each site
- - [ ] planning
- - [ ] pic
- - [ ] facilities
- - [ ] kindergarten
- - [ ] beforeafter
- - [ ] careers
- - [ ] wefi
- - [ ] french
- - [ ] register
- - [ ] returntoschool

**Comment by suzannezc** [comment]
### Configuration instructions

- Appearance > Menus
- - Max Mega Menu Settings > three dots, more options
- - - Menu Themes
- - - - Menu Bar
- - - - Mega Menus
- - - - Mobile Menu
- - - Menu Locations
- - - - Top Menu Region > Enabled

**Comment by suzannezc** [comment]
This change requires a theme change:  #524

**Comment by singhcwrdsb** [comment]
All tasks completed and tested successfully.
