### ISSUE TITLE
Add Max Mega Menu to schools (high schools)

### ISSUE THREAD

**Issue by suzannezc** [wrdsb/wordpress-theme#528]
## Prepare tracking

- [x] Copy this task list to an issue labelled deployment
- [x] Name issue: "add `plugin name` to `install(s)`"
- [x] Customize this task lists for unique tasks for this plugin

### Testing

- [x] Audition on WPLabs and `schoolswrdsb` (staging)
- [x] Identify installs/sites for use
- [x] Internal training on use
- [x] External training on use
- [x] Add to documentation
- [x] Closed beta testing
- [x] Open beta testing
- [x] Approved
### Initiate change process

- [x] [Submit Change Management Request](https://itservicedesk.wrdsb.ca/ITServiceDesk.WebAccess/wd/object/create.rails?class_name=ChangeManagement.Change&lifecycle_name=NewProcess211) (Major)
- [x] add issue url to Description of CMR "Changes tracked in GitHub: URL"
- [x] record the number in a comment on this issue
- [x] Add approval screenshots and PDF of email approval to Change Ticket
- [x] Attach rollout schedule to CMR https://docs.google.com/spreadsheets/d/1gE5lV2ac6ALY_Bh4HS-d8m6toseC8GxWHHP1uBP4OqI/edit#gid=0

#### For Menu
- [x] Enable Max Mega Menu in Appearances > Menus for the top-level navigation area
- [x] Configure Menu items to follow grid sub-menu layout if applicable (Ben will manage)
- [x] Configure for each site
> - [x] bci
> - [x] chc
> - [x] eci
> - [x] eds
> - [x] fhc
> - [x] gci
> - [x] GPS
> - [x] grc
> - [x] hrh
> - [x] jam
> - [x] jhs
> - [x] kci
> - [x] phs
> - [x] sss
> - [x] wci
> - [x] wod

## Close change
- [x] Add screenshots of successful change
- [x] Add PDF of email approval from client
- [x] Report change as successful
- [x] Update task list https://github.com/wrdsb/task-lists/blob/main/plugin-add.txt
- [x] Close this issue

**Comment by suzannezc** [comment]
CMR #2700

**Comment by singhcwrdsb** [comment]
Changes implemented successfully.
