### ISSUE TITLE
Add Max Mega Menu to schools (preparation)

### ISSUE THREAD

**Issue by suzannezc** [wrdsb/wordpress-theme#530]
## Prepare tracking

- [x] Copy this task list to an issue labelled deployment
- [x] Name issue: "add `plugin name` to `install(s)`"
- [x] Customize this task lists for unique tasks for this plugin

### Testing

- [x] Audition on WPLabs and `schoolswrdsb` (staging)
- [x] Identify installs/sites for use
- [x] Internal training on use
- [x] External training on use
- [ ] Add to documentation
- [x] Closed beta testing
- [x] Open beta testing
- [x] Approved
### Initiate change process

- [x] [Submit Change Management Request](https://itservicedesk.wrdsb.ca/ITServiceDesk.WebAccess/wd/object/create.rails?class_name=ChangeManagement.Change&lifecycle_name=NewProcess211) (standard)
- [x] add issue url to Description of CMR "Changes tracked in GitHub: URL"
- [x] record the number in a comment on this issue
- [x] Add approval screenshots and PDF of email approval to Change Ticket
- [x] Attach rollout schedule to CMR https://docs.google.com/spreadsheets/d/1gE5lV2ac6ALY_Bh4HS-d8m6toseC8GxWHHP1uBP4OqI/edit#gid=0

### Deployment
- [x] Install any base plugins required `Max Mega Menu` 
- [x] Install paid plugin `Max Mega Menu Pro`
- [x] https://github.com/wrdsb/wordpress-static/issues/4
- [x] #529 
- [x] create menu theme based on settings used on the corporate site #524, without the search and logo for desktop features

## Close change
- [x] Add screenshots of successful change
- [x] Add PDF of email approval from client
- [x] Report change as successful
- [x] Update task list https://github.com/wrdsb/task-lists/blob/main/plugin-add.txt
- [x] Close this issue

**Comment by suzannezc** [comment]
CMR 2697

**Comment by singhcwrdsb** [comment]
Change Successful.

**Comment by singhcwrdsb** [comment]
Change Successful.

**Comment by suzannezc** [comment]
@singhcwrdsb make sure you do the documentation, it's very important. we can walk through it together if you'd like! :) S
